# Generated by Django 3.1.1 on 2020-11-25 19:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Calendar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Class_Room',
            fields=[
                ('name', models.CharField(max_length=40, verbose_name='Room name')),
                ('description', models.TextField(max_length=400, verbose_name='Room description')),
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='Primary Key')),
                ('link_suffix', models.CharField(max_length=7, verbose_name='room link suffix')),
                ('creator_id', models.IntegerField(verbose_name='ID of room creator')),
            ],
        ),
        migrations.CreateModel(
            name='Day',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calendar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.calendar')),
            ],
        ),
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(max_length=5000, verbose_name='What are the topics')),
            ],
        ),
        migrations.CreateModel(
            name='Homework',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.day')),
            ],
        ),
        migrations.CreateModel(
            name='HW_Subject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(verbose_name='listing stuff todo')),
                ('lessson_name', models.CharField(max_length=200, verbose_name='lesson, eg. English')),
                ('homework', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.homework')),
            ],
        ),
        migrations.AddField(
            model_name='calendar',
            name='class_room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.class_room'),
        ),
    ]
