# Generated by Django 3.1.3 on 2020-11-28 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_auto_20201125_1906'),
    ]

    operations = [
        migrations.AddField(
            model_name='class_room',
            name='creation_date',
            field=models.DateField(default=None, verbose_name='date of creation'),
        ),
        migrations.AddField(
            model_name='hw_subject',
            name='creation_date',
            field=models.DateField(default=None),
        ),
    ]
